# Generated by Django 4.2.6 on 2023-10-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='12', max_length=15),
        ),
        migrations.AddField(
            model_name='dealer',
            name='phone_number',
            field=models.CharField(default='12', max_length=15),
        ),
    ]
